[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x', 'python3', 'make', 'gcc', 'sqlite']

[phases.install]
cmds = [
  'npm install --include=dev',
  'npm rebuild sqlite3',
  'cd client && npm install --include=dev'
]

[phases.build]
cmds = [
  'cd client && CI=false npm run build'
]

[start]
cmd = 'npm start'
