[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  'npm install --include=dev',
  'cd client && npm install --include=dev'
]

[phases.build]
cmds = [
  'cd client && CI=false npm run build'
]

[start]
cmd = 'npm start'
